### ISSUE TITLE
做的还需要加强 未来可期

### ISSUE THREAD

**Issue by loqhcn** [letwang/HookPHP#11]
文档, 官网 , 安装说明啥的, 期待越来越好！

**Comment by letwang** [comment]
> 文档, 官网 , 安装说明啥的, 都没做好,

目前抓紧研发核心代码 文档、官网的确有待改善。

**Comment by letwang** [comment]
补上了：
文档：https://github.com/letwang/HookPHP/wiki
官网：暂无
安装：https://github.com/letwang/HookPHP/wiki/Quick-Start
