### ISSUE TITLE
你好，我已经搭建起来了，然后要如何使用呢

### ISSUE THREAD

**Issue by xmlgrg** [letwang/HookPHP#19]
输入这些网址
127.0.0.1 www.iot.com
127.0.0.1 www.paas.com
127.0.0.1 www.payment.com
127.0.0.1 www.store.com

就显示
iot TOP
BOTTOM

**Comment by letwang** [comment]
https://github.com/letwang/HookPHP/wiki#3demo

访问http://www.admin.com:81 是完整功能，其他只是示例
