### ISSUE TITLE
项目开源值得点赞；dockerfile有点不规范啊，初始化环境文档不太友好

### ISSUE THREAD

**Issue by asyncpjax** [letwang/HookPHP#23]
另外，[hookphp的hub](https://hub.docker.com/r/letwang/hookphp)网址打不开了，能不能搞个国内平台的地址

**Comment by letwang** [comment]
去翻墙 搬梯子吧，可以解决一切烦恼。
打不开不是你的错，不要因为别人的错误去将就自己，直接去翻墙搬梯子 回归西方极乐世界。

dockerfile的确有点不规范，目前没太多精力去规范，只维持了Linix bash脚本，能跑就行了。

**Comment by letwang** [comment]
https://github.com/letwang/HookPHP/wiki

还行吧，有全新构建 也有一键开箱 都可以选择。
