### ISSUE TITLE
提个框架规范建议

### ISSUE THREAD

**Issue by dev-kang** [letwang/HookPHP#4]
1、不太理解vendor的Hook是做什么用的。如果需要使用composer，为何vendor中的hook不做成composer包？

2、PHP代码规范需要遵守一下，另外PRS4以及命名空间的使用尽量符合规范，这里不一一指出。

3、PHP的一些设计模式感觉怎么用，是否可以使用下减少代码的维护成本？

简单提一下个人建议，希望能有帮助。也希望此框架越做越好。

**Comment by letwang** [comment]
> 1、不太理解vendor的Hook是做什么用的。如果需要使用composer，为何vendor中的hook不做成composer包？
> 
> 2、PHP代码规范需要遵守一下，另外PRS4以及命名空间的使用尽量符合规范，这里不一一指出。
> 
> 3、PHP的一些设计模式感觉怎么用，是否可以使用下减少代码的维护成本？
> 
> 简单提一下个人建议，希望能有帮助。也希望此框架越做越好。

感谢关注，对应回答：
1.vendor是HookPHP系统及其下属各大平台(Admin、ERP、PAAS……)所使用的公有类库，尚未到稳定期，暂不分开管理，便于集中精力。
另外，此处已遵循YAF C扩展自动加载规则。
至于其他使用PHP Composer来管理的包，是不得已而为之的少数包，后面有同类C扩展时候，自然舍弃性能极差的PHP Composer，拥抱全C拓展扩充HookPHP。
2.从PSR0到现在，规范是人制定的，虽然PSR也在不断纠正升级，不过HookPHP却遵循了YAF中不得不遵循和行业通用的基本规范，其余的已经自成体系。
HookPHP只尊重规则带来的便利，不会为所谓的规范而束缚自身迅猛发展的脚步，除非有更多的无聊时间供HookPHP去消遣。
3.设计模式，目前已用的有工厂模式、单例模式、观察者模式。
其余的已经通过HookPHP中巧妙的文件位置、文件命名、方法命名、DB建模……实现了传统复杂模式才能实现的效果，且性能更高、扩展更强、代码更少、维护更易。
深入HookPHP，你会发现，规则是本系统核心亮点之一，规则即约定、规则即算法、规则即产出！
宇宙即规则，大道即规则，一心不动，大巧不工。

**Comment by LixinQian** [comment]
膜拜中

**Comment by debugHappy** [comment]
`
[yaf]
extension=yaf

yaf.use_namespace = 1

yaf.use_spl_autoload = 1

yaf.library = /home/letwang/workspace/HookPHP/vendor/

`
这个配置中 yaf.library = /home/letwang/workspace/HookPHP/vendor/
这样写不太好，如果我有多个yaf的项目怎么办呢、? 有可能我不是使用你的HookPHP做的

**Comment by letwang** [comment]
> `
> [yaf]
> extension=yaf
> 
> yaf.use_namespace = 1
> 
> yaf.use_spl_autoload = 1
> 
> yaf.library = /home/letwang/workspace/HookPHP/vendor/
> 
> `
> 这个配置中 yaf.library = /home/letwang/workspace/HookPHP/vendor/
> 这样写不太好，如果我有多个yaf的项目怎么办呢、? 有可能我不是使用你的HookPHP做的

独立主机（容器）部署，不存在你说的问题
如果的确需要　可以把此处配置删掉　用代码配置代替　不过性能可能差了一点
