### ISSUE TITLE
vendor目录代码注释

### ISSUE THREAD

**Issue by soldierm** [letwang/HookPHP#5]
虽然说代码就是最好的注释，但是vendor目录代码作为公共核心类库，每个var、method、class、trait最好能有详细的注释，便于开发者基于框架快速开发

**Comment by letwang** [comment]
少部分有注释，等HookPHP大业完成（PHP8 JIT未来的框架，集成12大业务，12大UI组件，支持用户插拔组件包），自有后来英雄完善注释，前期靠各位功底、悟性了～
