### ISSUE TITLE
想广谱不容易

### ISSUE THREAD

**Issue by wolix** [letwang/HookPHP#6]
看着作者的成果也是很赞。也想试用一下，不过——

最基础的Yaconf，到现在也没有针对php7.3的windows版本！win10子系统linux经过千辛万苦的pecl完了（原始代码需要修改才能通过），可选安装的另外两个也千辛万苦的安装完了，最后——忘记目的是要试用HookPHP了。

**Comment by letwang** [comment]
立马Linux Ubuntu啊，最友好的WINDOWS界面，我们本地WIN10装了个虚拟机，虚拟机里面是Ubuntu。
